### PR TITLE
Implement an external packages driver

### PR DESCRIPTION
**Pull request by peterebden**
This is still a bit numpty but seems to be moving roughly in the right direction. Is pretty relevant to us right now because we want to get gosec working which needs something like this.

Notes:
 - Doesn't honour all the flags / config etc. Have left some pertinent TODOs littered about the place.
 - It shells out to plz to get information. This works with the "API" we currently have but would be a lot cooler (and faster) if we had an SDK and could do it in-process.
 - Makes assumptions about the location of the stdlib (gross but seem to have little alternative)
 - Would be quite a bit nicer if we had one plz target per Go package (currently we may have multiple for a `go_module` which kinda sucks). If only someone were working on that...
 - I've fixed a bunch of stuff and think it mostly works; currently getting a bunch of weird messages which make me think something is messing up / overwriting files (there's a lot of weird `redeclared in this block` messages followed by lots of `undeclared name` which looks suspiciously like something has shit all over the top of the file, but haven't figured out what that means yet)

Anyway seems worth getting this up for a review before I spend more time on it.

### CODE REVIEW

**Comment by Tatskaari** [comment]
> It shells out to plz to get information. This works with the "API" we currently have but would be a lot cooler (and faster) if we had an SDK and could do it in-process.

My plan was to add a `#package_info` build def to `go_library()` and `go_module()` that spits out a json file that we can just read in in this tool. We can then just do `plz build -i go-package-info //some/path/...` and read those json files in. That way we get incrementalism, and move this logic out to the build defs!

**Comment by peterebden** [comment]
> > It shells out to plz to get information. This works with the "API" we currently have but would be a lot cooler (and faster) if we had an SDK and could do it in-process.
> 
> My plan was to add a `#package_info` build target to `go_library()` and `go_module()` that spits out a jsonl file that we can just read in in this tool. We can then just do `plz build -i go-package-info //some/path/...` and read those json files in. That way we get incrementalism, and move this logic out to the build defs!

Right, that's an interesting idea (also nice to be able to interrogate individual libraries that way). Will think on it.

**Review by Tatskaari — APPROVED** [review]
Happy for this to land! We can iterate later.  I might migrate the packages.go file to use it in the please_go tool to generate this at build time.

**Review by Tatskaari — APPROVED** [review]
Happy for this to land! We can iterate later.  I might migrate the packages.go file to use it in the please_go tool to generate this at build time.

**Comment by peterebden** [comment]
> Happy for this to land! We can iterate later. I might migrate the packages.go file to use it in the please_go tool to generate this at build time.

Thanks! I still want to work on it a bit - at least the current bug I mentioned above seems like some nonsense that I should be able to figure out

**Comment by peterebden** [comment]
Rebooting this in #53

**Pull request closed without merging**
